### ISSUE TITLE
Add WS connection timeout

### ISSUE THREAD

**Issue by Wondertan** [proximax-storage/nem2-sdk-go#101]

**Comment by slackve** [comment]
sets the connection's network read & write deadlines?

**Comment by Wondertan** [comment]
> sets the connection's network read & write deadlines?

No, program crushes when you are trying to connect to turned off or server. This should be handled

**Comment by slackve** [comment]
fixed up https://github.com/proximax-storage/nem2-sdk-go/pull/96/commits/31a695117091b5f510e1d8aa3f7051413d6e10f0
