### ISSUE TITLE
It is not possible to subscribe to one topic with many addresses

### ISSUE THREAD

**Issue by Wondertan** [proximax-storage/nem2-sdk-go#103]
```
sub1, _ := b.ws.Subscribe.Status("VBRPREMRDLANIF2WT2WRFXNLC5GDFGZYBVFSSAGK")
sub2, _ := b.ws.Subscribe.Status("VDYWAEJF7ZNGEOPAVGMSX6KDAX6PHVRENJVKX2OM")
```
Sub2 overrides sub1 programmatically, while websocket channel is still sending messages to sdk, which can't handle them

**Comment by slackve** [comment]
in your example do you use a single websocket connection for two accounts?

**Comment by slackve** [comment]
fixed up https://github.com/proximax-storage/nem2-sdk-go/pull/96/commits/6983f92a9a5bfc85602f3a619c3835248ff894d5
