### ISSUE TITLE
not receiving websocket block status updates

### ISSUE THREAD

**Issue by amurat** [proximax-storage/nem2-sdk-go#119]
issue with websocket code not receiving block status updates

`package main

import (
	"fmt"
	"github.com/proximax-storage/nem2-sdk-go/sdk"
)

const (
	baseUrl = "http://bctestnet1.xpxsirius.io:3000"
)

func main() {

	// timeout in milliseconds
	// 5000 ms = 5 seconds
	ws, err := sdk.NewConnectWs(baseUrl, 5000)
	if err != nil {
		panic(err)
	}

	fmt.Println("websocket negotiated uid:", ws.Uid)
	d, _ := ws.Subscribe.Block()

	for {
		data := <-d.Ch
		fmt.Printf("Block received with height: %v \n", data.Height)
	}
}
`

@slackve

**Comment by slackve** [comment]
The timeout is related to the reading of the socket, the blocks will be managed every 15 to 20 seconds. Your timeout should be higher. example: sdk.NewConnectWs(baseUrl, 25000)

**Comment by amurat** [comment]
don't think the issue is timeout related but lack of block updates

**Comment by amurat** [comment]
@slackve is there an error reporting mechanism in place for when the websocket closes due to timeout?

**Comment by slackve** [comment]
ws.Subscribe.Error("block") shows errors when reading websocket

**Comment by slackve** [comment]
````
func main() {
    // timeout in milliseconds 
    // 60000 ms = 60 seconds
    // 0 = without timeout
    ws, err := sdk.NewConnectWs(baseUrl, 600000)
   if err != nil {
        panic(err)
    }
    conf, err := sdk.NewConfig(baseUrl, networkType)
    if err != nil {
        panic(err)
    }
    // Use the default http client
    client := sdk.NewClient(nil, conf)

    fmt.Println("websocket negotiated uid:", ws.Uid)
    d, _ := ws.Subscribe.Block()
    if err != nil {
	fmt.Println(err)
    }

    e := ws.Subscribe.Error("block")

    for {
	select {

	case data := <-d.Ch:
		fmt.Printf("Block received with height: %v \n", data.Height)

		getBlockTransactions, resp, err := client.Blockchain.GetBlockTransactions(context.Background(), data.Height)

		if err != nil {
		    fmt.Printf("Blockchain.GetBlockTransactions returned error: %s", err)
		    return
		}
		fmt.Printf("Response Status Code == %d\n", resp.StatusCode)
		fmt.Printf("%s\n\n", getBlockTransactions)

	case err := <-e.Ch:
		e.Unsubscribe()
		panic(err.Error)
	}
    }
}
````

**Comment by slackve** [comment]
Solved in the new update
