### ISSUE TITLE
I'm getting an 'undefined: sdk.LoadTestnetConfig' error.

### ISSUE THREAD

**Issue by jonpecson** [proximax-storage/nem2-sdk-go#81]
Hello Sir,

I'm currently testing the 'Get AccountInfo for an account' sample code and I'm getting this error.

Sample code:

`package main

import (
	"fmt"

	"github.com/proximax-storage/nem2-sdk-go/sdk"
	"golang.org/x/net/context"
)

const (
	// Catapult-api-rest server.
	baseUrl = "http://localhost:3000"

	// Types of network.
	// MainNet:   104
	// TestNet:   152
	// Mijin:     96
	// MijinTest: 144
	networkType = sdk.MijinTest

	// A valid private key.
	publicKeyOne = "E17324EAF403B5FD747055ED3ED97CFD1000AF176FB9294C9424A2814D765A76"
)

// Simple Account API request
func main() {

	addressOne, _ := sdk.NewAddressFromPublicKey(publicKeyOne, networkType)

	conf, err := sdk.LoadTestnetConfig(baseUrl)
	if err != nil {
		panic(err)
	}

	// Use the default http client
	client := sdk.NewClient(nil, conf)

	// Get AccountInfo for an account.
	// Param address - A Address struct.
	accountInfo, resp, err := client.Account.GetAccountInfo(context.Background(), addressOne)
	if err != nil {
		fmt.Printf("Account.GetAccountInfo returned error: %s", err)
		return
	}
	fmt.Printf("Response Status Code == %d\n", resp.StatusCode)
	fmt.Printf(accountInfo.String())
}
`
Here's the screenshot: https://imgur.com/z8SuYKN

Thanks alot.

**Comment by alvin-reyes** [comment]
Thank you testing and raising this issue Jon. We'll look into it.
